### ISSUE TITLE
Redis on a remote host

### ISSUE THREAD

**Issue by rblazquez** [Alotor/grails-redis-hibernate-cache#2]
Plugin seems very interesting.
I want to know if it's possible to configure it to deal with a remote redis.

Thanks.

**Comment by Alotor** [comment]
Of course! 

It's just a wrapper over this library https://github.com/debop/hibernate-redis so it has the same functionality.

**Comment by rblazquez** [comment]
Thanks for answer.

I've seen that is a wrapper ... what features offer grails-redis-hibernate-cache in addition to hibernate-redis?

**Comment by Alotor** [comment]
Just an easier integration and configuration inside a Grails application but no additional features.

**Comment by rblazquez** [comment]
Thanks!

**Comment by Alotor** [comment]
You're welcome
